import FileSaver from "file-saver";
import {
    Button,
    Typography,
    makeStyles,
    Box,
    useTheme,
    Card,
    CardContent,
    TypographyProps,
    Grid,
} from "@material-ui/core";
import { Div, DivHor } from "../../components/base/Divs";

export default function Cert() {
    return (
        <>
            <Div style={{ width: "full-width" }}>
                <DivHor>
                    <img
                        src="https://i.im.ge/2022/06/17/r4U2pM.png"
                        // width="100"
                        height="250"
                    ></img>
                </DivHor>
                <DivHor>
                    <Typography
                        className="font-link"
                        style={{
                            marginTop: -70,
                            fontWeight: "500",
                            textAlign: "center",
                            fontSize: 70,
                        }}
                    >
                        {/* Carbon Credit */}
                        Certificate
                    </Typography>
                </DivHor>
                <DivHor>
                    <Typography
                        style={{
                            marginTop: -35,
                            fontWeight: "300",
                            textAlign: "center",
                            fontSize: 40,
                        }}
                    >
                        of Carbon Credit
                    </Typography>
                </DivHor>
                <DivHor style={{ width: "85vw", marginTop: 40 }}>
                    {" "}
                    <Grid item xs={6} style={{ alignItems: "center" }}>
                        <Typography
                            style={{
                                fontWeight: "300",
                                fontSize: 25,
                                textAlign: "center",
                            }}
                        >
                            Total energy cost of
                        </Typography>
                        <Typography
                            style={{
                                fontSize: 35,
                                fontWeight: "350",
                                textAlign: "center",
                            }}
                        >
                            23.03 kWh
                        </Typography>
                    </Grid>
                    <span
                        style={{
                            borderRightWidth: 1,
                            borderRightColor: "lightgray",
                            borderRightStyle: "solid",
                            alignSelf: "stretch",
                        }}
                    />
                    <Grid item xs={6} style={{ alignItems: "center" }}>
                        <Typography
                            style={{
                                fontWeight: "300",
                                fontSize: 25,
                                textAlign: "center",
                            }}
                        >
                            Generated by
                        </Typography>
                        <Typography
                            style={{
                                fontSize: 35,
                                fontWeight: "350",
                                textAlign: "center",
                            }}
                        >
                            ABDUIWHDINONFEOJ
                        </Typography>
                    </Grid>
                </DivHor>

                <Typography
                    style={{
                        textAlign: "center",
                        marginTop: 30,
                        fontSize: 15,
                        fontWeight: "300",
                    }}
                >
                    datetime : 06/12/2020 13:00 - 06/12/2020 14:00
                </Typography>
            </Div>
        </>
    );
}
